---
title: "Kodiak"
format: html
editor: visual
---

```{r}
library(sf)
library(leaflet)
library(tidyverse)
library(ggplot2)
library(ggspatial)
library(plotly)
library(geodata)
```

## Plan

### description

cycle information species information

variable information

### plot



### chart 

lakes in polys 

species in polys species in lakes 

## Data Loading

```{r}
gdb_path="AWC_2025_SpeciesEvents.gdb"
kodiak<-st_read("Kodiak_NWR.geojson")
kodiak <- st_transform(kodiak, 4326)
SPC_AL<-st_layers(gdb_path)
alaska <- gadm(country = "USA", level = 1, path = tempdir())  
alaska <- st_as_sf(alaska)
bbox_kodiak <- st_bbox(c(xmin = -155, xmax = -152, ymin = 56.6, ymax = 58.8), crs = st_crs(alaska))
kodiak_crop <- st_crop(alaska, bbox_kodiak)
```

```{r}
streams <- st_read(gdb_path, layer = "AWC_stream") %>%
  st_transform(crs = 4326)
lakes <- st_read(gdb_path, layer = "AWC_lake") %>%
  st_transform(crs = 4326)
polys <- st_read(gdb_path, layer = "AWC_poly")%>%
  st_transform(crs = 4326)
points <- st_read(gdb_path, layer = "AWC_point")%>%
  st_transform(crs = 4326)
ptEvents <- st_read(gdb_path, layer = "ptEvents")
```

```{r}
ptEvents <- ptEvents %>%
  filter(!is.na(LATITUDE) & !is.na(LONGITUDE)) %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326)
```

```{r}
pt_kodiak <- ptEvents %>%
  filter(
    grepl("KODIAK", QUAD), ignore.case = TRUE)%>%
  separate_rows(SPECIES, sep = ",")%>%
  mutate(QUAD=stringr::str_extract(QUAD, "[A-Z]-[0-9]+$"))
nrow(pt_kodiak )
```

```{r}
inside_idx <- st_within(points, kodiak) 
points_spatial_kodiak <- points[lengths(inside_idx) > 0, ]
points_spatial_kodiak<-st_join(points_spatial_kodiak, 
                         kodiak[, c("Index_ID")], 
                         join = st_within)


polys <- st_zm(polys, drop = TRUE, what = "ZM")
polys <- st_cast(polys, "MULTIPOLYGON", warn = FALSE)
polys <- st_make_valid(polys)
polys_union <- st_union(polys)
polys_touch_kodiak <- st_intersection(polys_union, kodiak)
# idx <- st_intersects(polys, kodiak)
# polys_touch_kodiak <- polys[lengths(idx) > 0, ]
```

```{r}
ggplot() +
  geom_sf(data = kodiak, fill = NA, color = "red") +
  geom_sf(data = polys_touch_kodiak, color="blue",fill = "blue", alpha = 0.4)+
  coord_sf()
```

```{r}
ggplot() +
  annotation_map_tile(type = "osm", zoomin = 0) +
  geom_sf(data = kodiak, aes(fill =Map_ID ), color = "red", alpha=0.2,size = 1) +
  geom_sf(data = points_spatial_kodiak, color = "black", size = 0.2) +
  labs(title = "Kodiak Points on Map") +
  theme_minimal()
```

```{r}
pts_coords <- st_coordinates(points_spatial_kodiak)
pts_df <- data.frame(lon = pts_coords[,1],
                     lat = pts_coords[,2],
                     lbl  = paste0("Lng: ", round(pts_coords[,1],2),
                                   "\tLat: ", round(pts_coords[,2],2)))
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(data = kodiak, color = "red", weight = 1, fill = FALSE) %>%
  addCircleMarkers(data = pts_df, lng = ~lon, lat = ~lat,
                   radius = 1, color = "blue",
                   label = ~lbl,)
```

```{r}
fish_stat<-points_spatial_kodiak%>%
  separate_rows(SPECIES, sep = ",")%>%
  tidyr::extract(SPECIES, into = c("SPECIES", "CYCLE"),
  regex = "([A-Z]+[A-Z]*)?([a-z]+)$", remove = FALSE)

poly_total <- fish_stat %>%
  st_drop_geometry() %>%
  count(Index_ID, name = "total_n")
poly_species <- fish_stat %>%
  st_drop_geometry() %>%
  count(Index_ID, SPECIES, name = "n")

kodiak_pt <- st_point_on_surface(kodiak)
kodiak_centers <- st_coordinates(kodiak_pt)
kodiak_centers <- kodiak %>%
  st_drop_geometry() %>%
  mutate(cx = kodiak_centers[,1],
         cy = kodiak_centers[,2]) %>%
  select(Index_ID, cx, cy)
ps <- poly_species %>%
  left_join(kodiak_centers, by = "Index_ID") %>%
  group_by(Index_ID) %>%
  mutate(
    angle = seq(0, 2*pi, length.out = n()),
    cx_j = cx + 0.03 * cos(angle),
    cy_j = cy + 0.03 * sin(angle)
  )

p <- ggplot() +
  geom_sf(data = kodiak_crop, fill = NA, color = "darkred", size = 0.1) +
  geom_sf(data = kodiak, fill = NA, color = "red", size = 0.11) +
  geom_point(data = ps,
             aes(x = cx_j, y = cy_j,
                 color = SPECIES,
                 size = n,
                 text = paste0("Poly: ", Index_ID,
                               "<br>Species: ", SPECIES,
                               "<br>Count: ", n))) +
  scale_size_continuous(range = c(2, 10)) +
  labs(color = "Species", size = "Count") +
  theme_minimal()+
  coord_fixed(ratio = 0.9)
  
ggplotly(p, tooltip = "text")


```

```{r}
fish_stat<-points_spatial_kodiak%>%
  tidyr::separate_rows(SPECIES, sep = ",")%>%
  tidyr::extract(SPECIES, into = c("SPECIES", "CYCLE"),
  regex = "([A-Z]+[A-Z]*)?([a-z]+)$", remove = FALSE)%>%
  filter(!is.na(LONGITUDE) & !is.na(LATITUDE))
fish_stat <- st_as_sf(fish_stat, coords = c("LONGITUDE", "LATITUDE"), crs = 4326)
lakes <- st_zm(lakes, drop = TRUE, what = "ZM")
lakes <- st_cast(lakes, "MULTIPOLYGON", warn = FALSE)
lakes <- st_make_valid(lakes)
streams <- st_zm(streams, drop = TRUE, what = "ZM")
streams <- st_cast(streams, "MULTILINESTRING", warn = FALSE)
streams <- st_make_valid(streams)
sf_use_s2(FALSE)
lakes_touch_kodiak <- st_intersection(lakes, kodiak)
streams_touch_kodiak <- st_intersection(streams, kodiak)
streams_touch_kodiak <- st_cast(streams_touch_kodiak, "MULTILINESTRING")
sf_use_s2(TRUE)

```


```{r}
p<-ggplot()+
  geom_sf(data = kodiak_crop, fill = NA, color = "black", size = 0.1) +
  geom_sf(data = kodiak, color = "red", alpha=0.1,size = 0.5) +
  geom_sf(data = lakes_touch_kodiak, color = "blue", size = 0.5) +
  geom_sf(data = streams_touch_kodiak, color = "blue", size = 0.5)+
  geom_sf(data = fish_stat, aes(color=SPECIES),alpha=0.3,size = 0.3)+
  theme_minimal()+
  coord_fixed(ratio=0.95)
ggplotly(p,tooltip = "text")


```

```{r}

fit_travel <- function(data = fish_stat, fish = "Chum Salmon") {
  data_filtered <- fish_stat%>%
    dplyr::filter(SPECIES == fish)
  p <- ggplot() +
    geom_sf(data = kodiak_crop, fill = NA, color = "black", size = 0.1) +
    geom_sf(data = kodiak, color = "red", alpha = 0.1, size = 0.5) +
    geom_sf(data = lakes_touch_kodiak, color = "blue", size = 0.5) +
    geom_sf(data = streams_touch_kodiak, color = "blue", size = 0.5) +
    geom_sf(data = data_filtered, aes(color = CYCLE), alpha = 0.7, size = 0.5) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = -45, hjust = 1, vjust = 1)) +
    coord_sf()
  ggplotly(p, tooltip = c("SPECIES", "CYCLE"))
}
fit_travel()
```



```{r}
fish_stat <- fish_stat %>%
  mutate(
    SPECIES = case_when(
      SPECIES == "CO" ~ "Coho Salmon",
      SPECIES == "S"  ~ "Sockeye Salmon",
      SPECIES == "DV" ~ "Dolly Varden",
      SPECIES == "SH" ~ "Sheefish",
      SPECIES == "CH" ~ "Chum Salmon",
      SPECIES == "P"  ~ "Pink Salmon",
      SPECIES == "K"  ~ "King (Chinook) Salmon",
      TRUE ~ SPECIES
    ),
    CYCLE = case_when(
      CYCLE == "p"  ~ "parr",
      CYCLE == "pr" ~ "parr–resident",
      CYCLE == "r"  ~ "resident",
      CYCLE == "rs" ~ "resident–smolt",
      CYCLE == "s"  ~ "smolt",
      CYCLE == "sr" ~ "smolt–resident",
      CYCLE == "ps" ~ "parr–smolt",
      TRUE ~ CYCLE
    )
  )
out_gpkg <- "kodiak_analysis_layers.gpkg"

# delete old file to avoid layer conflicts
if (file.exists(out_gpkg)) file.remove(out_gpkg)

st_write(kodiak, out_gpkg, layer = "kodiak", delete_layer = TRUE)
st_write(kodiak_crop, out_gpkg, layer = "kodiak_crop", delete_layer = TRUE)
st_write(points_spatial_kodiak, out_gpkg,
         layer = "awc_points_kodiak", delete_layer = TRUE)
st_write(fish_stat, out_gpkg,
         layer = "fish_stat", delete_layer = TRUE)
st_write(lakes_touch_kodiak, out_gpkg,
         layer = "lakes_touch_kodiak", delete_layer = TRUE)
st_write(streams_touch_kodiak, out_gpkg,
         layer = "streams_touch_kodiak", delete_layer = TRUE)

```



